server:
  port: 8081

spring:
  application:
    name: carparkInfo
  datasource:
    url: jdbc:mysql://localhost:3306/carparkdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/scripts
    baseline-on-migrate: true